ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
endif::arc42help[]

In this section we will describe the approach taken to develop the system. First we address the technologies used in the project and then the architecture used.

=== Technologies

The following technologies are used in our project:

* *React*: To build the web application's UI, we will use this technology due to its simplicity and its ability to create reusable components. It has also been chosen as it has a relatively gentle learning curve (as we will be learning while building).
* *NodeJS*: To develop the backend part of the system, we will use NodeJS due to its ease to develop server-side operations (compared to plain JavaScript). Furthermore, it is a well-known technology for this type of projects and it provides some key features that we will need, such as the ability to handle multiple requests at the same time and the fact that it is an event-driven language.
* *MongoDB*: To store the data of the system, we will use MongoDB due to its flexibility and scalability.
* *Docker*: To deploy the system, we will use this technology due to its portability and reliability.
* #TBD# Choose the LLM: We are still deciding which LLM to use. We are considering using one of the following:
** Gemini
** Qwen
** Mistral
* #TBD# Choose the deployment platform: We will probably use a cloud platform to deploy the system, but this will be decided later.
* *Git & GitHub*: For version control and collaboration, we will use Git and GitHub. These tools will enable the team to collaborate efficiently and keep track of changes, issues and documentation.
* #TBD# Elaborate on CI/CD: We will probably use GitHub Actions to automate the CI/CD process, but this will be elaborated later.

=== Architecture

The architecture used in the system will be based on the following parts:

* *Microservices* for the different core functionalities of the system. This way we can develop each service independently and scale them as needed. Additionally, this approach will allow us to use different technologies if needed.
* *Gateway* to allow communication within services, ensuring cohesion in the system.
