ifndef::imagesdir[:imagesdir: ../images]

[[section-concepts]]
== Cross-cutting Concepts
=== Internacionalization
In hopes of incresing accessibility for our users, we want to give our application the ability of playing in different languages.

We are starting off only offering English and Spanish, but this offer may be expanded in the future with different prototypes.

As we know that internacionalization is more than just changing the language of the text in the game, we will have to look further into some library that will make these feature easier to implement.

Our first prototype won't be capable of changing the language, but hopefully in the future it will. 



=== Security

We also want our users to not only have fun while playing our game, but feel safe. For this purpose, we use the following characteristics:

- **Bcrypt**: used to securely hash and store user passwords, protecting them from breaches. Its adaptive nature makes it resistant to brute-force attacks, ensuring robust user authentication.

- **JWT** (JSON Web Token): it enables secure, stateless user authentication. It allows users to stay logged in without storing session data on the server, enhancing scalability and providing a secure way to transmit user data between client and server.

=== Testing
We want our team to pay lots of attention to testing while developing the app. A correct testing suite can ensure that the app is evolving correctly and that we won't have problems in the future.

For this, we are using **jest** and testing each individual service as well as the endpoints in the gateway service, before they connect to the webapp directory (front-end).